# Generated by Django 3.1.1 on 2020-11-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_comment_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('urgent', 'Urgent'), ('normal', 'Normal'), ('not_important', 'Not Important')], default='not_important', max_length=100),
        ),
    ]
