# Generated by Django 3.1.1 on 2020-11-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_tickets_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='status',
            field=models.CharField(choices=[('Open', 'open'), ('Pending', 'pending'), ('Closed', 'closed')], default='Open', max_length=100),
        ),
    ]
