# Generated by Django 3.1.3 on 2020-12-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20201117_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
