# Generated by Django 3.1.3 on 2021-01-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20201207_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
